name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install -r app/requirements-dev.txt
      - name: Lint
        run: |
          black --check app/
          isort --check-only app/
          flake8 app/
      - name: Test
        run: pytest --cov=app tests/
