name: Deploy Infraestrutura

on:
  push:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/deploy-infra.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Instalar Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Configurar credenciais do cluster
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Aplicar manifests base
        run: kubectl apply -k infrastructure/base/

      - name: Aplicar overlay dev
        if: github.ref == 'refs/heads/dev'
        run: kubectl apply -k infrastructure/overlays/dev/

      - name: Aplicar overlay prod
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod'
        run: kubectl apply -k infrastructure/overlays/prod/